// app/login/page.tsx
	// Auto-generated by Theme Editor - Do not edit manually

	import ClientPage from './ClientPage';

	export async function generateMetadata() {
		return {
			title: "Login",
			description: "",
		};
	}

	export default function GeneratedPage() {
		// Embedded theme and page data
		const themeData = {
        "company_id": 1,
        "company_uid": "1BUPSJZ67YZ",
        "date_added": "2026-07-07 13:37:37",
        "hosting_info": {
            "github_client_id": "Ov23liumfD4QjywcPtSo",
            "github_repo_clone_url": "https://github.com/oluwapaso/ikeja-properties.git",
            "github_repo_default_branch": "main",
            "github_repo_description": "This is a repo for ikeja properties website",
            "github_repo_full_name": "oluwapaso/ikeja-properties",
            "github_repo_html_url": "https://github.com/oluwapaso/ikeja-properties",
            "github_repo_language": "\u003cnil\u003e",
            "github_repo_name": "ikeja-properties",
            "github_repo_ssh_url": "git@github.com:oluwapaso/ikeja-properties.git",
            "github_repo_updated_at": "2026-07-07T12:57:02Z",
            "github_repo_visibility": "public"
        },
        "idx_theme_id": 4,
        "idx_theme_uid": "cd35e11a-e4f4-41c7-86b2-02b23ce753c4",
        "status": "Draft",
        "theme_settings": {
            "bg_solid_primary_color": "bg-sky-600",
            "blog_card": "BlogCard-1",
            "channel_name": "Ikorodu oga channel ",
            "channel_uid": "28315dc0-7d11-458a-a40e-80844cb27861",
            "channel_website": "https://ikeja-properties.vercel.app",
            "footer_component": {
                "props": {
                    "button_text": "Send Us Message",
                    "category": "footers",
                    "component": "FooterVar6",
                    "header": "Want To Talk",
                    "name": "Dune 3",
                    "sub_header": "It's all about the humans behind a brand and those experiencing it, we're right there. In the middle.",
                    "type": "section"
                },
                "type": "FooterVar6"
            },
            "footer_menu": [
                {
                    "sub_menu": [
                        {
                            "link": "/buying-homes-in-lekki",
                            "title": "Buying Homes"
                        },
                        {
                            "link": "/selling-homes-in-lekki",
                            "title": "Selling Homes"
                        }
                    ],
                    "title": "Discover Services"
                },
                {
                    "sub_menu": [
                        {
                            "link": "/buying-homes-in-lekki",
                            "title": "Buying Homes"
                        },
                        {
                            "link": "/selling-homes-in-lekki",
                            "title": "Selling Homes"
                        }
                    ],
                    "title": "Popular links"
                }
            ],
            "header_component": "Header-1",
            "is_default": "No",
            "name": "theme name here",
            "nav_component": {
                "props": {
                    "button_text": "Send Us Message",
                    "category": "navs",
                    "component": "NavVar2",
                    "header": "Want To Talk",
                    "name": "Derera",
                    "sub_header": "It's all about the humans behind a brand and those experiencing it, we're right there. In the middle.",
                    "type": "section"
                },
                "type": "NavVar2"
            },
            "pages": [],
            "primary_button_text": "rose-50",
            "primary_color": "rose-600",
            "primary_font": "font-plus-jakarta",
            "property_card": "PropertyCard-1",
            "secondary_button_text": "sky-50",
            "secondary_color": "sky-600",
            "secondary_font": "font-libre-baskerville",
            "service_card": "ServiceCard-1",
            "solid_primary_color": "green-600",
            "solid_secondary_color": "gray-800",
            "solid_tetiary_color": "amber-600",
            "tetiary_button_text": "rose-50",
            "tetiary_color": "rose-600",
            "theme_prefix": "",
            "top_menu": [
                {
                    "link": "/home",
                    "title": "Home"
                },
                {
                    "sub_menu": [
                        {
                            "link": "/buying-homes-in-lekki",
                            "title": "Buying Homes"
                        },
                        {
                            "link": "/selling-homes-in-lekki",
                            "title": "Selling Homes"
                        }
                    ],
                    "title": "Our Services"
                }
            ],
            "version": "1.0.1"
        },
        "title": "Ikeja Properties",
        "user_id": 1
    };
		const pageData = {
        "isDefault": true,
        "isHome": false,
        "isPublished": false,
        "lastPublished": "",
        "metaDescription": "Login page description for SEO",
        "sections": [
            {
                "props": {
                    "button_text": "Sign In",
                    "category": "login",
                    "component": "LoginFormVar1",
                    "component_index": 0,
                    "header": "Login",
                    "name": "Accosted Armoury",
                    "sub_header": "Provide Your CredentiaLs to Login Into Your Account",
                    "type": "section"
                },
                "type": "LoginFormVar1"
            }
        ],
        "slug": "/login",
        "title": "Login",
        "uid": "login-001"
    };

		return <ClientPage themeData={themeData} pageData={pageData} googleFontsURL="https://fonts.googleapis.com/css2?family=Plus+Jakarta:wght@400;500;600;700&family=Libre+Baskerville:wght@400;500;600;700&display=swap" />;
	}