import type { Metadata, Viewport } from "next";
import Script from "next/script";
import "@/app/globals.css";
import { Providers } from "@/app/GlobalRedux/providers";
import ThemeSettings from "@/components/ThemeSettings";
import PageLoaderMain from "@/components/PageLoaderMain";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
    title: "Homely",
    description: "Generated by create next app",
}

// 2. Place the viewport export here, outside the component
export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1.0,
    maximumScale: 1.0,
    userScalable: false, // Next.js converts false to "no" automatically
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
                <Script src={`${process.env.NEXT_PUBLIC_MLS_URL}/ads/v1/mls-hub-sdk.js`} strategy="beforeInteractive" />
                <link href={`${process.env.NEXT_PUBLIC_MLS_URL}/ads/v1/ad-styles.css`} rel="stylesheet" />
            </head>
            <body className="font-poppins font-medium">
                <Providers>
                    <ThemeSettings theme_name="Default Theme" />
                    {children}
                    <PageLoaderMain />
                    <ToastContainer />
                </Providers>
            </body>
        </html>
    )
    // return (<body>{children}</body>)
}
