import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { Providers } from "@/app/GlobalRedux/providers";
import PageLoaderMain from "@/components/PageLoaderMain";
import { ToastContainer } from "react-toastify";
import Script from "next/script";
import ThemeSettings from "@/components/ThemeSettings";
import PropertyModal from "@/components/modals/PropertyModal";
import PopUpAds from "@/components/ads/PopUpAds";

export const metadata: Metadata = {
  title: "Preview Page",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <Script src={`${process.env.NEXT_PUBLIC_MLS_URL}/ads/v1/mls-hub-sdk.js`} strategy="beforeInteractive" />
        <link href={`${process.env.NEXT_PUBLIC_MLS_URL}/ads/v1/ad-styles.css`} rel="stylesheet" />

        {/* === CRITICAL: Force Google Fonts for Iframe === */}
        {/* <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Roboto:wght@400;500;600;700&family=Poppins:wght@400;500;600;700&family=Montserrat:wght@400;500;600;700&family=Open+Sans:wght@400;500;600;700&family=Lato:wght@400;500;600;700&family=Playfair+Display:wght@400;500;600;700&family=Raleway:wght@400;500;600;700&family=Nunito:wght@400;500;600;700&family=Ubuntu:wght@400;500;600;700&family=DM+Sans:wght@400;500;600;700&family=Figtree:wght@400;500;600;700&family=Outfit:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&family=Manrope:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@400;500;600;700&family=Work+Sans:wght@400;500;600;700&family=Source+Sans+3:wght@400;500;600;700&family=IBM+Plex+Sans:wght@400;500;600;700&family=Libre+Baskerville:wght@400;500;600;700&family=Merriweather:wght@400;500;600;700&family=PT+Serif:wght@400;500;600;700&family=EB+Garamond:wght@400;500;600;700&family=Crimson+Text:wght@400;500;600;700&family=Jost:wght@400;500;600;700&family=Quicksand:wght@400;500;600;700&family=Mulish:wght@400;500;600;700&family=Barlow:wght@400;500;600;700&family=Karla:wght@400;500;600;700&family=Heebo:wght@400;500;600;700&family=Lexend:wght@400;500;600;700&family=Urbanist:wght@400;500;600;700&family=Instrument+Sans:wght@400;500;600;700&family=Geist:wght@400;500;600;700&family=Geist+Mono:wght@400;500;600;700&display=swap" rel="stylesheet" /> */}

      </head>
      <body className={`antialiased dark:bg-dark-main`} >
        <Providers>
          <ThemeSettings theme_name="Default Theme" />
          {children}
          <PageLoaderMain />
          <PropertyModal />
          <PopUpAds />
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
